// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgnUQFG4OixujGgGQ-PlXI1VF_-BGUizc',
    appId: '1:44767048258:web:1e65e0f2c65d4f3b23f3db',
    messagingSenderId: '44767048258',
    projectId: 'flutter-note-ca68f',
    authDomain: 'flutter-note-ca68f.firebaseapp.com',
    storageBucket: 'flutter-note-ca68f.firebasestorage.app',
    measurementId: 'G-EEPFC8KB9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlK_Hu17ixRPH2Ojpu_UIbZ38bzYiGe24',
    appId: '1:44767048258:android:d02eed80976bdc1d23f3db',
    messagingSenderId: '44767048258',
    projectId: 'flutter-note-ca68f',
    storageBucket: 'flutter-note-ca68f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfwQMhiygeESFsCS6ze1CrISUbAhf0nik',
    appId: '1:44767048258:ios:ba06dcc03b77380e23f3db',
    messagingSenderId: '44767048258',
    projectId: 'flutter-note-ca68f',
    storageBucket: 'flutter-note-ca68f.firebasestorage.app',
    iosBundleId: 'com.example.flutterNote',
  );
}
